name: Automated Evaluation

on:
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: x64

      # Runs the evalution script
      - name: Run eval script
        run: |
          set +e
          python eval/run_eval.py --id ${{github.head_ref}} >& out.txt
          output=$(cat out.txt)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=log::$output"
        id: eval

      # Updates pull request
      - name: Update pull request
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            # For debugging
            # console.log(`${{ steps.eval.outputs.log }}`)
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Output of eval script:\n\`\`\`\n${{ steps.eval.outputs.log }}\n\`\`\`\n`
            })
